name: MSI-Tracer
channels:
  - defaults
dependencies:
  - biopython=1.72=py35h830ac7b_0
  - blas=1.0=mkl
  - bleach=3.1.4=py_0
  - ca-certificates=2020.1.1=0
  - certifi=2018.8.24=py35_1
  - colorama=0.4.3=py_0
  - cycler=0.10.0=py35hcc71164_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.2.3=py35_2
  - freetype=2.9.1=ha9979f8_1
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - intel-openmp=2020.1=216
  - ipykernel=4.10.0=py35_0
  - ipython=5.8.0=py35_0
  - ipython_genutils=0.2.0=py35ha709e79_0
  - ipywidgets=7.4.1=py35_0
  - jinja2=2.11.2=py_0
  - jpeg=9b=hb83a4c4_2
  - jsonschema=2.6.0=py35h27d56d3_0
  - jupyter=1.0.0=py35_7
  - jupyter_client=5.3.3=py_0
  - jupyter_console=5.2.0=py35_1
  - jupyter_core=4.5.0=py_0
  - kiwisolver=1.0.1=py35h6538335_0
  - libpng=1.6.37=h2a8f88b_0
  - libsodium=1.0.16=h9d3ae62_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.0=py35hfa6e2cd_1
  - matplotlib=3.0.0=py35hd159220_0
  - mistune=0.8.3=py35hfa6e2cd_1
  - mkl=2020.1=216
  - msys2-conda-epoch=20160418=1
  - nbconvert=5.5.0=py_0
  - nbformat=5.0.6=py_0
  - notebook=5.6.0=py35_0
  - numpy=1.14.2=py35h5c71026_0
  - openssl=1.1.1g=he774522_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py35_1
  - pickleshare=0.7.4=py35h2f9f535_0
  - pip=10.0.1=py35_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=1.0.15=py35h89c7cb4_0
  - pygments=2.6.1=py_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py35h6538335_2
  - python=3.5.6=he025d50_0
  - python-dateutil=2.8.1=py_0
  - pytz=2020.1=py_0
  - pywin32=223=py35hfa6e2cd_1
  - pywinpty=0.5.4=py35_0
  - pyzmq=17.1.2=py35hfa6e2cd_0
  - qt=5.9.7=vc14h73c81de_0
  - qtconsole=4.7.4=py_0
  - qtpy=1.9.0=py_0
  - send2trash=1.5.0=py35_0
  - setuptools=40.2.0=py35_0
  - simplegeneric=0.8.1=py35_2
  - sip=4.19.8=py35h6538335_0
  - six=1.11.0=py35_1
  - sqlite=3.31.1=h2a8f88b_1
  - terminado=0.8.1=py35_1
  - testpath=0.4.4=py_0
  - tornado=5.1.1=py35hfa6e2cd_0
  - tqdm=4.46.0=py_0
  - traitlets=4.3.2=py35h09b975b_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_1
  - wcwidth=0.1.9=py_0
  - webencodings=0.5.1=py35_1
  - wheel=0.31.1=py35_0
  - widgetsnbextension=3.4.1=py35_0
  - win_unicode_console=0.5=py35h56988b5_0
  - wincertstore=0.2=py35hfebbdb8_0
  - winpty=0.4.3=4
  - zeromq=4.2.5=he025d50_1
  - zlib=1.2.11=h62dcd97_4
prefix: C:\Users\Alex Makri\.conda\envs\MSI-Tracer

